# Generated by Django 3.0.2 on 2020-02-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
